spring:
  application:
    name: backend

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  cors:
    allowed-origins: " " # per default cors is not allowed. Is set such that CorsConfig.java can be instanciated.

# Enable only health actuator endpoint per default
management:
  endpoints:
    web:
      exposure:
        include: health
