spring:
  application:
    name: backend

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  cors:
    allowed-origins: "https://leanlearnfrontend-production.up.railway.app"
