name: build and push backend image

on:
  push:
    branches: [main, dev, feature/setupBackend] # remove feature branch after closed
    paths:
      - "backend/**"

  build-and-push-backend-image:
    on:
      paths:
        - "backend/**"

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -f ./backend/Dockerfile -t ghcr.io/${{ github.repository_owner }}/backend_lean_learn:latest -t ghcr.io/${{ github.repository_owner }}/backend_lean_learn:${{ github.sha }} ./frontend

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend_lean_learn:latest
          docker push ghcr.io/${{ github.repository_owner }}/backend_lean_learn:${{ github.sha }}
