name: simple check that echos "hello"

on: push

jobs:
  build-and-push-frontend-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/my-image:latest ./frontend

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/my-image:latest
