name: Playwright Tests
on:
  push:
    # paths:
    #   - "frontend/**"
    branches:
      - "**"
  pull_request:
    paths:
      - "frontend/**"
    branches: [main, dev]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          # cache: npm
          cach-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend Docker image
        run: docker build -t frontend-test ./frontend

      - name: Run frontend container
        run: docker run -d -p 5713:80 --name frontend-app frontend-test

      - name: Wait for frontend
        run: npx wait-on http://localhost:5713

      - name: Install Playwright Browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: frontend
        env:
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:5713
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
